// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    401: typeof import('./src/components/error/401.vue')['default']
    404: typeof import('./src/components/error/404.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    ATable: typeof import('ant-design-vue/es')['Table']
    Breadcrumb: typeof import('./src/components/breadcrumb.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Heads: typeof import('./src/components/Heads.vue')['default']
    LeftNav: typeof import('./src/components/nav/leftNav.vue')['default']
    LoginFooter: typeof import('./src/components/login/loginFooter.vue')['default']
    LoginHeader: typeof import('./src/components/login/loginHeader.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    Refs: typeof import('./src/components/Refs.vue')['default']
    RightToolbar: typeof import('./src/components/RightToolbar/index.vue')['default']
    Select: typeof import('./src/components/Select/index.vue')['default']
    Suspense: typeof import('./src/components/Suspense.vue')['default']
    Tags: typeof import('./src/components/nav/Tags.vue')['default']
    TopNav: typeof import('./src/components/nav/topNav.vue')['default']
    Ueditor: typeof import('./src/components/Ueditor/index.vue')['default']
  }
}

export { }
