// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    401: typeof import('./components/error/401.vue')['default']
    404: typeof import('./components/error/404.vue')['default']
    AppLink: typeof import('./components/AppLink.vue')['default']
    Breadcrumb: typeof import('./components/breadcrumb.vue')['default']
    DefaultSiderBar: typeof import('./components/Public/Sidebars/DefaultSiderBar.tsx')['default']
    Heads: typeof import('./components/Heads.vue')['default']
    JHoverBtn: typeof import('./components/JHoverBtn.vue')['default']
    LeftNav: typeof import('./components/nav/leftNav.vue')['default']
    LoginFooter: typeof import('./components/login/loginFooter.vue')['default']
    LoginHeader: typeof import('./components/login/loginHeader.vue')['default']
    MyTable: typeof import('./components/table/MyTable.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    Pagination: typeof import('./components/Pagination/index.vue')['default']
    Refs: typeof import('./components/Refs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/Select/index.vue')['default']
    Suspense: typeof import('./components/Suspense.vue')['default']
    Table: typeof import('./components/table/index.vue')['default']
    TableFilter: typeof import('./components/TableFilter/index.vue')['default']
    TableFormRow: typeof import('./components/table/TableFormRow.jsx')['default']
    Tags: typeof import('./components/nav/Tags.vue')['default']
    ToolBar: typeof import('./components/toolBar.vue')['default']
    TopNav: typeof import('./components/nav/topNav.vue')['default']
    Ueditor: typeof import('./components/Ueditor/index.vue')['default']
    Upload: typeof import('./components/Upload/index.vue')['default']
  }
}

export {}
